// src/icons.ts
import {
  faTachometerAlt,
  faFileInvoiceDollar,
  faRobot,
  faBook,
  faHistory,
  faChartLine,
  faShieldAlt,
  faBars,
  faBell,
  faChevronDown,
  faReceipt,
  faExclamationTriangle,
  faCheckCircle,
  faFileAlt,
  faListUl,
  faArrowLeft,
  faStopCircle,
  faUserCheck,
  faHourglassHalf,
//   faSkullCrosswalk,
  faStamp,
  faBan,
  faPlusCircle,
  faSearch,
  faMicrochip,
  faBrain,
  faQuoteRight,
  faGavel,
  faHandcuffs,
  faLightbulb,
  faDatabase,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  tachometerAlt: faTachometerAlt,
  fileInvoiceDollar: faFileInvoiceDollar,
  robot: faRobot,
  book: faBook,
  history: faHistory,
  chartLine: faChartLine,
  shieldAlt: faShieldAlt,
  bars: faBars,
  bell: faBell,
  chevronDown: faChevronDown,
  receipt: faReceipt,
  exclamationTriangle: faExclamationTriangle,
  checkCircle: faCheckCircle,
  fileAlt: faFileAlt,
  listUl: faListUl,
  arrowLeft: faArrowLeft,
  stopCircle: faStopCircle,
  userCheck: faUserCheck,
  hourglassHalf: faHourglassHalf,
//   skullCrosswalk: faSkullCrosswalk,
  stamp: faStamp,
  ban: faBan,
  plusCircle: faPlusCircle,
  search: faSearch,
  microchip: faMicrochip,
  brain: faBrain,
  quoteRight: faQuoteRight,
  gavel: faGavel,
  handcuffs: faHandcuffs,
  lightbulb: faLightbulb,
  database: faDatabase,
};
